<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Icons\bookmark.png" />
    <None Remove="Icons\comment.png" />
    <None Remove="Icons\like.png" />
    <None Remove="Icons\nolike.png" />
    <None Remove="Icons\post1.jpg" />
    <None Remove="Icons\post2.jpg" />
    <None Remove="Icons\post3.jpg" />
    <None Remove="Icons\send.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Icons\like.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Speech" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Icons\bookmark.png" />
    <Resource Include="Icons\comment.png" />
    <Resource Include="Icons\nolike.png" />
    <Resource Include="Icons\post1.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\post2.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\post3.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\send.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
